[package]
name = "Ptdetest"
version = "0.1.0"
edition = "2024"

[dependencies]
hudhook = "0.7.0"
imgui = "0.12.0"
mem-rs = "0.2.4"
tracing-subscriber = "0.3.20"
lazy_static = "1.5.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hello_hud"
